[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.16.2"
rand = "0.8.4"
crossbeam = "0.8"
threadpool = "*"
image = "0.24.1"
num_cpus = "1.13.1"
